import 'micromark-util-types'

declare module 'micromark-util-types' {
  interface TokenTypeMap {
    wikiLink: 'wikiLink'
    wikiLinkMarker: 'wikiLinkMarker'
    wikiLinkValue: 'wikiLinkValue'
    wikiLinkHeading: 'wikiLinkHeading'
    wikiLinkHeadingMarker: 'wikiLinkHeadingMarker'
    wikiLinkBlockId: 'wikiLinkBlockId'
    wikiLinkBlockIdMarker: 'wikiLinkBlockIdMarker'
    wikiLinkAlias: 'wikiLinkAlias'
    wikiLinkAliasMarker: 'wikiLinkAliasMarker'
    embed: 'embed'
    embedMarker: 'embedMarker'
    embedValue: 'embedValue'
    tag: 'tag'
    tagMarker: 'tagMarker'
    tagValue: 'tagValue'
    callout: 'callout'
    calloutMarker: 'calloutMarker'
    calloutType: 'calloutType'
    calloutTypeMarker: 'calloutTypeMarker'
    calloutTitle: 'calloutTitle'
    highlight: 'highlight'
    highlightMarker: 'highlightMarker'
    highlightValue: 'highlightValue'
    comment: 'comment'
    commentMarker: 'commentMarker'
    commentValue: 'commentValue'
    footnoteReference: 'footnoteReference'
    footnoteReferenceMarker: 'footnoteReferenceMarker'
    footnoteReferenceId: 'footnoteReferenceId'
    footnoteInline: 'footnoteInline'
    footnoteInlineMarker: 'footnoteInlineMarker'
    footnoteInlineValue: 'footnoteInlineValue'
    footnoteDefinition: 'footnoteDefinition'
    footnoteDefinitionMarker: 'footnoteDefinitionMarker'
    footnoteDefinitionId: 'footnoteDefinitionId'
    footnoteDefinitionValue: 'footnoteDefinitionValue'
    blockReference: 'blockReference'
    blockReferenceMarker: 'blockReferenceMarker'
    blockReferenceId: 'blockReferenceId'
    mathInline: 'mathInline'
    mathInlineMarker: 'mathInlineMarker'
    mathInlineValue: 'mathInlineValue'
    mathBlock: 'mathBlock'
    mathBlockFence: 'mathBlockFence'
    mathBlockValue: 'mathBlockValue'
  }
}
