declare module 'micromark-util-symbol' {
  export const codes: {
    carriageReturn: number
    lineFeed: number
    carriageReturnLineFeed: number
    horizontalTab: number
    space: number
    exclamationMark: number
    quotationMark: number
    numberSign: number
    dollarSign: number
    percentSign: number
    ampersand: number
    apostrophe: number
    asterisk: number
    plusSign: number
    comma: number
    hyphen: number
    dash: number
    fullStop: number
    solidus: number
    slash: number
    digit0: number
    digit9: number
    colon: number
    semicolon: number
    lessThan: number
    equalsTo: number
    greaterThan: number
    questionMark: number
    atSign: number
    uppercaseA: number
    uppercaseZ: number
    leftSquareBracket: number
    backslash: number
    rightSquareBracket: number
    circumflexAccent: number
    caret: number
    underscore: number
    graveAccent: number
    lowercaseA: number
    lowercaseZ: number
    leftCurlyBrace: number
    verticalLine: number
    rightCurlyBrace: number
    tilde: number
    eof: number
    tab: number
    leftParenthesis: number
    rightParenthesis: number
  }

  export const constants: {
    attentionSideBefore: number
    attentionSideAfter: number
    atxHeadingOpeningFenceSizeMax: number
    autolinkDomainSizeMax: number
    autolinkSchemeSizeMax: number
    characterEscape: number
    characterReferenceNamed: number
    characterReferenceNumericDecimal: number
    characterReferenceNumericHexadecimal: number
    characterReferenceSizeMax: number
    codeFencedSequenceSizeMin: number
    hardBreakPrefixSizeMin: number
    htmlRaw: number
    htmlComment: number
    htmlInstruction: number
    htmlDeclaration: number
    htmlCdata: number
    htmlBasic: number
    htmlFlow: number
    linkResourceDestinationBalanceMax: number
    linkResourceSizeMax: number
    linkTitleDestinationBalanceMax: number
    listItemValueSizeMax: number
    listSpread: number
    listSpreadSizeMin: number
    listTight: number
    nonterminatingLineEndingSize: number
    orderedListMarkerMinSize: number
    phrasingContent: number
    tabSize: number
    thematicBreakMarkerCountMin: number
  }

  export const types: {
    attentionSequence: string
    autolink: string
    autolinkEmail: string
    autolinkProtocol: string
    atxHeading: string
    atxHeadingSequence: string
    blockQuote: string
    blockQuotePrefix: string
    blockQuoteWhitespace: string
    break: string
    characterEscape: string
    characterEscapeValue: string
    characterReference: string
    characterReferenceMarker: string
    characterReferenceMarkerNumeric: string
    characterReferenceMarkerHexadecimal: string
    characterReferenceValue: string
    codeFenced: string
    codeFencedFence: string
    codeFencedFenceInfo: string
    codeFencedFenceMeta: string
    codeFlow: string
    codeText: string
    codeTextData: string
    codeTextPadding: string
    codeTextSequence: string
    content: string
    data: string
    definition: string
    definitionDestination: string
    definitionDestinationLiteral: string
    definitionDestinationRaw: string
    definitionLabel: string
    definitionMarker: string
    definitionTitle: string
    definitionTitleString: string
    definitionTitleWhitespace: string
    document: string
    escape: string
    escapeMarker: string
    escapeValue: string
    flow: string
    hardBreakEscape: string
    hardBreakTrailing: string
    headingAtx: string
    headingAtxSequence: string
    headingSetext: string
    headingSetextUnderline: string
    headingSetextUnderlineSequence: string
    htmlFlow: string
    htmlFlowData: string
    htmlText: string
    htmlTextData: string
    image: string
    label: string
    labelEnd: string
    labelEndImage: string
    labelEndLink: string
    labelLink: string
    labelStart: string
    labelStartImage: string
    labelStartLink: string
    labelStartFootnote: string
    labelText: string
    labelTracker: string
    lineEnding: string
    lineEndingBlank: string
    linePrefix: string
    listItem: string
    listItemIndent: string
    listItemMarker: string
    listItemValue: string
    listOrdered: string
    listUnordered: string
    newline: number
    null: string
    paragraph: string
    raw: string
    resource: string
    resourceDestination: string
    resourceDestinationLiteral: string
    resourceDestinationRaw: string
    resourceMarker: string
    resourceTitle: string
    resourceTitleMarker: string
    resourceTitleString: string
    resourceTitleWhitespace: string
    setextUnderline: string
    setextUnderlineSequence: string
    space: string
    spaceMarker: string
    spaceSize: number
    spaceValue: string
    strong: string
    strongSequence: string
    strongValue: string
    text: string
    textPlaceholder: string
    thematicBreak: string
    thematicBreakSequence: string
    whitespace: string
  }
}
